# Generated by Django 6.0 on 2026-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='founded_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.DateField(),
        ),
    ]
